/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ImageProcesser;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author AM Developers
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private JFileChooser fileChooser;
    private File file;
    private JFrame jFrame;
    private JLabel container;

    public MainView() {
        initComponents();
        fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose File to apply Sobal/Laplacian");
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter(".png", ".png"));
        fileChooser.setCurrentDirectory(new File(""));

        container = new JLabel();
        container.setSize(choosedImage.getWidth(), choosedImage.getHeight());
        jFrame = new JFrame("sobel");
        jFrame.setBounds(this.getBounds());
        jFrame.add(container);
        jFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseFile = new javax.swing.JButton();
        choosedImage = new javax.swing.JLabel();
        applySobel = new javax.swing.JButton();
        laplacianButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chooseFile.setText("Choose File");
        chooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileActionPerformed(evt);
            }
        });

        applySobel.setText("Apply Sobel");
        applySobel.setEnabled(false);
        applySobel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applySobelActionPerformed(evt);
            }
        });

        laplacianButton.setText("Apply Laplacian");
        laplacianButton.setEnabled(false);
        laplacianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laplacianButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("ChooseFile");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Help");

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(chooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238)
                .addComponent(applySobel)
                .addGap(42, 42, 42)
                .addComponent(laplacianButton)
                .addContainerGap(356, Short.MAX_VALUE))
            .addComponent(choosedImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applySobel)
                    .addComponent(laplacianButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choosedImage, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileActionPerformed
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            ImageIcon imageIcon = new ImageIcon(file.toString());
            Image myImage = imageIcon.getImage();
            myImage = myImage.getScaledInstance(choosedImage.getWidth(), choosedImage.getHeight(), Image.SCALE_SMOOTH);
            imageIcon.setImage(myImage);
            choosedImage.setIcon(imageIcon);
            applySobel.setEnabled(true);
            laplacianButton.setEnabled(true);
            System.out.println(file.getName());
        } else if (result == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "Cancel was selected");
        }


    }//GEN-LAST:event_chooseFileActionPerformed

    private void applySobelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applySobelActionPerformed
        // TODO add your handling code here:
        BufferedImage output = ImageProcessor.convertToSobel(file);
        ImageIcon imageIcon = new ImageIcon(output);
        Image myImage = imageIcon.getImage();
        myImage = myImage.getScaledInstance(choosedImage.getWidth(), choosedImage.getHeight(), Image.SCALE_SMOOTH);
        imageIcon.setImage(myImage);
        container.setIcon(imageIcon);

        jFrame.setVisible(true);
    }//GEN-LAST:event_applySobelActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        chooseFileActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void laplacianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laplacianButtonActionPerformed
        LaplacianOperator laplacianOperator = new LaplacianOperator(file.toString());
        ImageIcon imageIcon = new ImageIcon("laplacian.jpg");
        Image myImage = imageIcon.getImage();
        myImage = myImage.getScaledInstance(choosedImage.getWidth(), choosedImage.getHeight(), Image.SCALE_SMOOTH);
        imageIcon.setImage(myImage);
        container.setIcon(imageIcon);

        jFrame.setVisible(true);


    }//GEN-LAST:event_laplacianButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applySobel;
    private javax.swing.JButton chooseFile;
    private javax.swing.JLabel choosedImage;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton laplacianButton;
    // End of variables declaration//GEN-END:variables
}
